### ISSUE TITLE
Panic on connection to podman dameon using TCP

### ISSUE THREAD

**Issue by K4rakara** [marhkb/pods#532]
### Reproduction steps

1. Expose a podman daemon using tcp
2. Connect to that podman daemon
3. Panic!

This is the full backtrace, which I had to compile the program myself to get:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/model/container.rs:331:47
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:111:5
   3: core::option::Option<T>::unwrap
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/option.rs:778:21
   4: pods::model::container::Container::new::{{closure}}
             at ./Build/pods/src/model/container.rs:331:29
   5: core::option::Option<T>::map
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/option.rs:925:29
   6: pods::model::container::Container::new
             at ./Build/pods/src/model/container.rs:324:17
   7: pods::model::container_list::ContainerList::refresh::{{closure}}::{{closure}}
             at ./Build/pods/src/model/container_list.rs:336:57
   8: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/iter/traits/iterator.rs:828:29
   9: core::iter::adapters::filter::filter_fold::{{closure}}
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/iter/adapters/filter.rs:37:44
  10: core::iter::traits::iterator::Iterator::fold
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/iter/traits/iterator.rs:2414:21
  11: <core::iter::adapters::filter::Filter<I,P> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/iter/adapters/filter.rs:101:9
  12: core::iter::traits::iterator::Iterator::for_each
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/iter/traits/iterator.rs:831:9
  13: pods::model::container_list::ContainerList::refresh::{{closure}}
             at ./Build/pods/src/model/container_list.rs:326:25
  14: pods::utils::do_async::{{closure}}
             at ./Build/pods/src/utils.rs:309:9
  15: <futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll
             at ./Build/pods/_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.25/src/future_obj.rs:84:18
  16: <glib::main_context_futures::FutureWrapper as core::future::future::Future>::poll
             at ./Build/pods/_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.16.7/src/main_context_futures.rs:32:44
  17: glib::main_context_futures::TaskSource::poll::{{closure}}
             at ./Build/pods/_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.16.7/src/main_context_futures.rs:233:17
  18: glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default
             at ./Build/pods/_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.16.7/src/main_context.rs:156:12
  19: glib::main_context_futures::TaskSource::poll
             at ./Build/pods/_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.16.7/src/main_context_futures.rs:226:9
  20: glib::main_context_futures::TaskSource::dispatch
             at ./Build/pods/_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/glib-0.16.7/src/main_context_futures.rs:67:34
  21: g_main_context_dispatch
  22: <unknown>
  23: g_main_context_iteration
  24: g_application_run
  25: <O as gio::application::ApplicationExtManual>::run_with_args
             at ./Build/pods/_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/gio-0.16.7/src/application.rs:35:13
  26: <O as gio::application::ApplicationExtManual>::run
             at ./Build/pods/_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/gio-0.16.7/src/application.rs:28:9
  27: pods::application::Application::run
             at ./Build/pods/src/application.rs:216:9
  28: pods::main
             at ./Build/pods/src/main.rs:90:5
  29: core::ops::function::FnOnce::call_once
```

### Environment

- Pods version: `v1.1.0-beta.1-2-g0df4289`
- Containerized via flatpak

**Comment by K4rakara** [comment]
Upon inspecting the code, this appears to be happening because the only part of the port mapping that gets read is the protocol, not the host/container port, ip address, etc. I would say that would be the root issue, but on a local unix socket connection I don't have the same issue.

**Comment by marhkb** [comment]
Thanks for reporting. 
Reading the documentation, it seems that Podman uses a random port if the field `host_port` is omitted.

> HostPort is the port number that will be forwarded from the host into the container. If omitted, a random port on the host (guaranteed to be over 1024) will be assigned.

But in this case, it shouldn't do this because of `--publish 5173:80`.

> but on a local unix socket connection I don't have the same issue.

This is indeed weird. What version of Podman are you using?

**Comment by K4rakara** [comment]
I'm using podman version `4.3.1`

**Comment by marhkb** [comment]
Yeah, probably. The version is so old it even isn't listed anymore on the API reference overview :-)
https://docs.podman.io/en/latest/Reference.html

For my understanding: You are using the unix socket for `4.3.1` and the TCP socket for `3.0.1`? 

I think there wouldn't be an error if you'd expose the `4.3.1` via TCP podman instance and connect to that?

I will try to setup a VM with that particular podman version for reproduction purposes in the next days.

**Comment by K4rakara** [comment]
Correct, that's the setup (a certified Debian moment if I say so myself)

In the meantime I'll try to see if I can use a backport of a newer podman on the server.

**Comment by marhkb** [comment]
What you could also try is to change the problematic line
https://github.com/marhkb/pods/blob/b036fd2c824704a05bd6e150eb2c2f9366eee3ed/src/model/container.rs#L331

To somethting like this
```rust
mapping.host_port.unwrap_or(80),
```

In this we, we can check whether more errors may follow

**Comment by K4rakara** [comment]
It looks like everything works after that! I can view the images, containers, processes, etc all just fine.

**Comment by marhkb** [comment]
Ok, I've set up the debian VM. The problem is that podman 3.0 uses camelCase for its field names
```
❯ curl http://bullseye:37017/v3.0.1/libpod/containers/json
[{"AutoRemove":false,"Command":["/bin/sh"],"Created":"2023-01-30T20:58:12.329067206+01:00","CreatedAt":"","Exited":false,"ExitedAt":-62135596800,"ExitCode":0,"Id":"9c6a10c729bfbbc5d9fee00e645daa4839bfca68a5a425d8cd7fdf3e9fd8c517","Image":"docker.io/library/alpine:latest","ImageID":"042a816809aac8d0f7d7cacac7965782ee2ecac3f21bcf9f24b1de1a7387b769","IsInfra":false,"Labels":null,"Mounts":[],"Names":["flagrant-record"],"Namespaces":{},"Networks":["podman"],"Pid":797,"Pod":"","PodName":"","Ports":[{"hostPort":5555,"containerPort":5555,"protocol":"tcp","hostIP":""}],"Size":null,"StartedAt":1675108693,"State":"running","Status":""}]
```

Since 3.1 podman uses snake_case
```
"Ports":[{"host_ip":"","container_port":35017,"host_port":35017,"range":1,"protocol":"tcp"}],
```

See the [documentation](https://docs.podman.io/en/latest/_static/api.html?version=v3.1#tag/containers/operation/ContainerListLibpod)

Unfortunately, the library `podman-api-rs`, which Pod uses, doesn't cover this.

I can work around this specific issue by showing a "?" instead of an actual port number. But IMHO, it would be the best approach to upgrade to `3.1` since `3.0` is basically undocumented at this point.

**Comment by marhkb** [comment]
I decided to not show the port if it is absence. Please feel free to report all the bugs you encounter! Let's see how many of them we can actually fix.
